"""Finalized projects table

Revision ID: 53f620f9d7f3
Revises: c82198fb3779
Create Date: 2020-10-24 21:05:56.031354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f620f9d7f3'
down_revision = 'c82198fb3779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('estimated_hours_required', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('project_description', sa.String(length=300), nullable=True))
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'project_description')
    op.drop_column('projects', 'estimated_hours_required')
    op.drop_column('projects', 'due_date')
    op.drop_column('projects', 'created_by')
    # ### end Alembic commands ###
