"""added tasks, table representations, status and various other changes

Revision ID: daf64f1f355c
Revises: 1c1aaf51fe6b
Create Date: 2020-10-24 21:42:02.851269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf64f1f355c'
down_revision = '1c1aaf51fe6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'status', ['status'], ['id'])
    op.add_column('tasks', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'status', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'status')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'status')
    op.drop_table('status')
    # ### end Alembic commands ###
